name: Deploy to GitHub Pages

on:
  push: 
    branches:   
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: Use Node.js (Latest)
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
    - name: Build
      run: |
         npm install -g @angular/cli
         npm install
         ng build
         cp dist/index.html dist/404.html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
          branch: gh-pages    # The branch the action should deploy to.
          folder: dist        # The folder the action should deploy.
          token: ${{ secrets.ACCESS_TOKEN }}